services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:2024.07.0
    restart: unless-stopped
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: 'PASSWORD'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "IP_HOST:53:53/tcp"
      - "IP_HOST:53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    cap_add:
      - NET_ADMIN
